model:
  base_learning_rate: 5.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: LR_image
    concat_mode: False
    image_size: 64
    channels: 3
    monitor: val/loss_simple_ema
    cond_stage_trainable: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions: [ 1, 2, 4, 8]
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4,4 ]
        num_head_channels: 32

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 3
        monitor: "val/rec_loss"
        ckpt_path: /home/cindy/PycharmProjects/latent-diffusion/configs/trained_models/2023-01-27T13-32-24_ae_kl_64x64x3_zeus/checkpoints/last.ckpt
#        n_embed: 8192
        ddconfig:
          double_z: True
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4 ]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_first_stage__
#    cond_stage_config:
#       target: ldm.modules.encoders.modules.SpatialRescaler
#       params:
#         n_stages: 2
#         in_channels: 182
#         out_channels: 3
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 1
    wrap: False
    train:
      target: ldm.data.LOL.LOLTrain
      params:
        size: 256
        data_root: /home/cindy/PycharmProjects/data/LOL/our485
    validation:
      target: ldm.data.LOL.LOLValidation
      params:
        size: 256
        data_root: /home/cindy/PycharmProjects/data/LOL/eval15


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True